# Generated by Django 6.0.2 on 2026-03-25 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Supplier',
            new_name='supplier',
        ),
    ]
