# Generated by Django 6.0.2 on 2026-03-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_supplier_purchase_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='item_total_price',
            new_name='item_total_cost',
        ),
        migrations.RenameField(
            model_name='purchaseitem',
            old_name='price',
            new_name='unit_cost',
        ),
    ]
