# Generated by Django 6.0.2 on 2026-02-28 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projuct',
            new_name='Product',
        ),
    ]
