# Generated by Django 6.0.2 on 2026-03-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_projuct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('l', 'Liter'), ('g', 'Gram'), ('m', 'Meter'), ('box', 'Box'), ('pack', 'Pack')], default='pcs', max_length=20),
        ),
    ]
