# Generated by Django 6.0.2 on 2026-04-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_rate',
            field=models.DecimalField(blank=True, choices=[('0', '0%'), ('0.25', '0.25%'), ('3', '3%'), ('5', '5%'), ('12', '12%'), ('18', '18%'), ('28', '28%')], decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryledger',
            name='transaction_type',
            field=models.CharField(choices=[('pur', 'Purchase'), ('sale', 'Sale'), ('new_product', 'New Product Added'), ('adj', 'Adjustment'), ('return_in', 'Return In'), ('return_out', 'Return Out'), ('dmg', 'Damage'), ('cancel_sale', 'Cancel Sale')], db_index=True, max_length=20),
        ),
    ]
