# Generated by Django 6.0.2 on 2026-03-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Pieces'), ('kg', 'Kilogram'), ('l', 'Liter'), ('g', 'Gram'), ('m', 'Meter'), ('box', 'Box'), ('pack', 'Pack')], max_length=20),
        ),
    ]
