# Generated by Django 6.0.2 on 2026-04-29 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tax_rate',
            field=models.CharField(blank=True, choices=[('0', '0%'), ('0.25', '0.25%'), ('3', '3%'), ('5', '5%'), ('12', '12%'), ('18', '18%'), ('28', '28%')], max_length=10, null=True),
        ),
    ]
