# Generated by Django 6.0.2 on 2026-03-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_product_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
    ]
