# Generated by Django 6.0.2 on 2026-03-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_category_productcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'Piece'), ('kg', 'KG'), ('l', 'Liter'), ('g', 'Gram'), ('m', 'Meter'), ('box', 'Box'), ('pack', 'Pack')], max_length=20),
        ),
    ]
