# Generated by Django 6.0.2 on 2026-03-21 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantity',
            new_name='quantity',
        ),
    ]
