# Generated by Django 6.0.2 on 2026-03-21 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_stock_quantity_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='stock_quantity',
        ),
    ]
