# Generated by Django 6.0.2 on 2026-03-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_quantity_product_stock_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('pur', 'Purchase'), ('sale', 'Sale'), ('adj', 'Adjustment'), ('return_in', 'Return In'), ('return_out', 'Return Out'), ('dmg', 'Damage')], db_index=True, max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('before_quantity', models.IntegerField()),
                ('after_quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(choices=[('pur', 'Purchase'), ('sale', 'Sale'), ('adj', 'Adjustment')], max_length=20)),
                ('reference_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
        ),
    ]
