# Generated by Django 6.0.2 on 2026-03-25 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryledger'),
        ('purchase', '0003_rename_item_total_price_purchaseitem_item_total_cost_and_more'),
        ('sales', '0007_rename_item_total_saleitem_item_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryledger',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RemoveField(
            model_name='inventoryledger',
            name='reference_id',
        ),
        migrations.RemoveField(
            model_name='inventoryledger',
            name='reference_type',
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchase.purchase'),
        ),
        migrations.AddField(
            model_name='inventoryledger',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sales.sale'),
        ),
    ]
