# Generated by Django 6.0.2 on 2026-03-29 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_rename_product_id_inventoryledger_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost_price',
            new_name='current_avg_cost',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='stock_quantity',
            new_name='current_stock',
        ),
    ]
