# Generated by Django 6.0.2 on 2026-03-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleitem_unit_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
