# Generated by Django 6.0.2 on 2026-03-05 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_saleitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
    ]
