# Generated by Django 6.0.2 on 2026-03-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_customer_options_customer_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleitem',
            old_name='item_total',
            new_name='item_total_price',
        ),
    ]
